services:
  n8n:
    build:
      context: ./
      dockerfile: docker/images/n8n-custom/Dockerfile
    container_name: n8n
    environment:
      N8N_PORT: 5678
      N8N_HOST: localhost
      N8N_PROTOCOL: http
      N8N_PUBLIC_API_URL: http://localhost:5678
      N8N_USER_MANAGEMENT_DISABLED: "true"
      N8N_BASIC_AUTH_ACTIVE: "false"
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    tmpfs:
      - /tmp  # Helps with performance & avoiding disk issues

volumes:
  n8n_data:
